Bump minitest versions to 5.14.3 (#148)
On an upcoming commit I was getting spec failures because the locked version of minitest does not work with rails 3.1.1, so bumping to one that should work: https://github.com/seattlerb/minitest/blob/master/History.rdoc#5143--2021-01-05-

```
minitest-5.14.2 requires ruby version < 3.1, >= 2.2, which is incompatible with
the current version, ruby 3.1.1p18
Error: Process completed with exit code 5.
```